name: Airdrop Notifier

on:
  schedule:
    - cron: '0 0 * * *' # 毎日09:00 JSTに実行
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Node.js をセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Puppeteer の依存をインストール
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            fonts-liberation \
            libappindicator3-1 \
            libasound2 \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libgdk-pixbuf2.0-0 \
            libnspr4 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            xdg-utils \
            wget

      - name: NPM パッケージをインストール
        run: npm install

      - name: スクレーパーを実行
        run: node index.js

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
