name: スクレイピングと通知

on:
  schedule:
    - cron: '0 0 * * *' # 毎日 0:00 に実行
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4

    - name: Node.jsをセットアップ
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 依存パッケージをインストールする
      run: npm ci

    - name: 環境変数を設定（OpenAI API Key）
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: echo "✅ OpenAI Key Set"

    - name: スクリプトを実行（ChatGPT評価付き）
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: node index.js

    - name: Output.txtを保存
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: output.txt
