name: 通知する

on:
  schedule:
    - cron: '0 1 * * *' # 毎日10:00 JST（UTCで1:00）
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4

    - name: Node.jsをセットアップする
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 依存パッケージをインストールする
      run: npm install

    - name: 環境変数を設定（OpenAI API Key）
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
        echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}" >> $GITHUB_ENV

    - name: スクリプトを実行（ChatGPT評価付き）
      run: node index.js
