name: Run Airdrop Notifier

on:
  schedule:
    - cron: '0 0 * * *' # 毎日0時（UTC）= 日本時間09:00
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies for Puppeteer
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ca-certificates \
            fonts-liberation \
            libatk-bridge2.0-0 \
            libatk1.0-0 \
            libcups2 \
            libdbus-1-3 \
            libgdk-pixbuf2.0-0 \
            libnspr4 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxrandr2 \
            libxss1 \
            libxtst6 \
            xdg-utils \
            wget \
            libx11-6 \
            libxext6 \
            libxfixes3 \
            libglib2.0-0 \
            libgtk-3-0 \
            libxrender1 \
            libxi6 \
            libgbm1

      - name: Install NPM packages
        run: npm install

      - name: Run scraper
        run: node index.js
