name: Run Airdrop Notifier

on:
  workflow_dispatch:

jobs:
  analyze-airdrops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run script with OpenAI API key
        run: node index.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
